config/routes.rb
Rails.application.routes.draw do
  root "pages#home"

  resources :artworks do
    resources :images
  end

  scope :admin do
    resources :users
  end

  namespace :curator do
    resources :artworks, only: [:index, :show]
  end

  devise_for :users
  devise_scope :user do
    get "login", to: "devise/sessions#new"
    delete "logout", to: "devise/sessions#destroy"
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/artwork.rb
class Artwork < ApplicationRecord
  validates :title, :medium, :location, :year, presence: true
  validates :units, inclusion: {in: %w[in cm],
                                message: "%{value} is not a valid unit"}

  validate :dimensions

  belongs_to :user
  has_many :images, dependent: :destroy

  def more_images_allowed?
    images.count < 3
  end

  private

  def dimensions
    if duration.blank? && (height.blank? || width.blank?)
      errors.add(:either, "Height and Width or Duration is required")
    end
  end
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :artwork
  has_one_attached :file

  validates :caption, :file, presence: true
  validate :valid_image

  before_destroy :purge_file

  def is_video?
    file.blob.content_type.include?("video")
  end

  private

  def valid_image
    return unless file.attached?
    unless file.blob.byte_size <= 10.megabyte
      errors.add(:file, "is too large")
    end

    unless /^image|video/.match?(file.content_type)
      errors.add(:file, "must be a JPEG, PNG, or Video")
    end
  end

  def purge_file
    file.purge
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :lockable,
    :recoverable, :rememberable, :trackable, :validatable

  enum :role, [:artist, :curator, :admin]

  validates :email, :last_name, :role, presence: true

  has_many :artworks, dependent: :destroy

  def name
    [first_name, last_name].compact.join(" ")
  end

  def show_artworks?
    artist? || admin?
  end

  def show_browse?
    curator? || admin?
  end

  def show_users?
    admin?
  end

  def active_for_authentication?
    super && active?
  end

  def more_artworks_allowed?
    artworks.count < 10
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController
  before_action :authenticate_user!
  before_action :confirm_not_curator
  before_action :set_artwork, only: %i[show edit update destroy]

  # GET /artworks
  def index
    @artworks = current_user.artworks
  end

  # GET /artworks/1
  def show
  end

  # GET /artworks/new
  def new
    @artwork = Artwork.new
  end

  # GET /artworks/1/edit
  def edit
  end

  # POST /artworks
  def create
    redirect_to artworks_url, notice: "You have uploaded the maximum number of artworks" unless current_user.more_artworks_allowed?

    @artwork = Artwork.new(artwork_params)
    @artwork.user = current_user

    if @artwork.save
      redirect_to @artwork, notice: "Artwork was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /artworks/1
  def update
    if @artwork.update(artwork_params)
      redirect_to @artwork, notice: "Artwork was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /artworks/1
  def destroy
    @artwork.destroy!
    redirect_to artworks_url, notice: "Artwork was successfully destroyed.", status: :see_other
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_artwork
    @artwork = current_user.artworks.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def artwork_params
    params.require(:artwork).permit(:title, :medium, :description, :price, :visible, :duration, :units, :height, :width, :depth, :location, :user_id, :year, :edition)
  end

  def confirm_not_curator
    if current_user.curator?
      redirect_to root_url, notice: "You do not have access to that page"
    end
  end
end

app/controllers/curator/artworks_controller.rb
class Curator::ArtworksController < ApplicationController
  before_action :authenticate_user!
  before_action :confirm_curator

  # GET /curator/artworks
  def index
    @artworks = Artwork.all.limit(30)
  end

  # GET /curator/artworks/1
  def show
    @artwork = Artwork.find(params[:id])
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_curator_artwork
    @curator_artwork = Curator::Artwork.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def curator_artwork_params
    params.fetch(:curator_artwork, {})
  end

  def confirm_curator
    current_user.show_browse?
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_artwork
  before_action :set_image, only: %i[show edit update destroy]

  # GET /images
  def index
    @images = @artwork.images
  end

  # GET /images/1
  def show
  end

  # GET /images/new
  def new
    @image = @artwork.images.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  def create
    @image = @artwork.images.new(image_params)

    if @image.save
      redirect_to @artwork
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /images/1
  def update
    if @image.update(image_params)
      redirect_to artwork_images_url(@artwork), notice: "Image was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /images/1
  def destroy
    @image.destroy!
    redirect_to @artwork, status: :see_other
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_image
    @image = @artwork.images.find(params[:id])
  end

  def set_artwork
    @artwork = current_user.artworks.find(params[:artwork_id])
  end

  # Only allow a list of trusted parameters through.
  def image_params
    params.require(:image).permit(:caption, :file)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :confirm_admin
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users
  def index
    @users = User.all.order(id: :desc).limit(100)
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: "User was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: "User was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy!
    redirect_to users_url, notice: "User was successfully destroyed.", status: :see_other
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:email, :name, :role)
  end

  def confirm_admin
    unless current_user.admin?
      redirect_to root_url, notice: "You do not have access to that page"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def thumbnail_url(image)
    if image.is_video?
      "#{image.file.url}/ik-thumbnail.jpg?tr=h-100"
    else
      image.file.url(transformation: [{height: 100, quality: 100, raw: "c-at_max"}])
    end
  end

  def large_url(image)
    if image.is_video?
      "#{image.file.url}/ik-thumbnail.jpg?tr=h-400"
    else
      image.file.url(transformation: [{height: 400, quality: 100, raw: "c-at_max"}])
    end
  end

  def asset_delete_text(i)
    if i.is_video?
      "Delete video"
    else
      "Delete image"
    end
  end
end

app/views/artworks/_artwork.html.erb
<%= turbo_frame_tag "artwork_#{artwork.id}" do %>
  <div id="<%= dom_id artwork %>">
    <tr>
      <td><%= artwork.id %></td>
      <td><%= link_to artwork.title, artwork %></td>
      <td><%= artwork.medium %></td>
      <td><%= artwork.description %></td>
      <td><%= artwork.visible ? "yes" : "no" %></td>
      <td>
        <% artwork.images.each do |image| %>
          <%= image_tag thumbnail_url(image)  %>
        <% end %>
      </td>
      <td>
        <%= button_to "Delete", artwork, method: :delete, form: { data: { turbo_confirm: 'Are you sure?' } }, class: "btn btn-sm btn-danger" %>
      </td>
    </tr>
  </div>
<% end %>

app/views/artworks/_dimensions.html.erb
<div>
  <% if @artwork.duration %>
    <%= @artwork.duration %> minutes <br>
  <% end %>
  <% if @artwork.height %>
    <%= @artwork.height %> x <%= @artwork.width %>
    <% if @artwork.depth %>
      x <%= @artwork.depth %>
    <% end %>
    <%= @artwork.units %>
  <% end %>
</div>

app/views/artworks/_form.html.erb
  <%= bootstrap_form_with(model: artwork) do |f| %>
  <%= f.alert_message "Please fix the errors below." %>
  <%= f.text_field :title, help: "required" %>
  <%= f.text_field :medium, help: "required" %>
  <%= f.text_field :edition, help: "if applicable" %>
  <%= f.text_area :description %>
  <%= f.number_field :year, help: "required" %>
  <%= f.number_field :price %>
  <%= f.text_field :location, help: "required" %>
  <%= f.check_box :visible, label: "Visible to curators?" %>
  <fieldset class="border p-2 mb-4">
    <p class="text-secondary">Either duration or heigh and width are required</p>
    <%= f.number_field :duration, label: "Duration (minutes)" %>
    <%= f.select :units, %w[in cm] %>
    <%= f.number_field :height %>
    <%= f.number_field :width %>
    <%= f.number_field :depth %>
  </fieldset>
  <%= f.submit "Save" %>
<% end %>

app/views/artworks/_image.html.erb
<div class="col-4" data-src="%<= i.file.url %>">
  IMAGE
  <%= image_tag large_url(i), alt: i.caption %>
  <i><%= i.caption %></i>
</div>

app/views/artworks/edit.html.erb
<div class="container col-md-5">
  <h4>Editing artwork</h4>
  <%= render "form", artwork: @artwork %>
  <br>
  <div>
    <%= link_to "Show this artwork", @artwork %> |
    <%= link_to "Back to artworks", artworks_path %>
  </div>
</div>

app/views/artworks/index.html.erb
  
<h4>Add up to 10 Artworks</h4>
<% if current_user.more_artworks_allowed? %>
  <%= link_to "Add new artwork", new_artwork_path, class: "btn btn-secondary mt-2 mb-3" %>
<% end %>
<table class="table">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Title</th>
      <th scope="col">Medium</th>
      <th scope="col">Description</th>
      <th scope="col">Visible to curators?</th>
      <th scope="col">&nbsp;</th>
      <th scope="col">&nbsp;</th>
    </tr>
  </thead>
  <tbody id="artworks">
    <% @artworks.each do |artwork| %>
      <%= render artwork %>
    <% end %>
  </table>
</div>

app/views/artworks/new.html.erb
<div class="container col-md-5">
  <h4>New artwork</h4>
  <%= render "form", artwork: @artwork %>
</div>

app/views/artworks/show.html.erb
<div class="container">
  <section class="image-grid">
    <div class="row gy-4" data-controller="lightbox">
      <% images = @artwork.images %>
      <% images.each do |i| %>
        <a href="<%= i.file.url %>">
          <%= image_tag large_url(i) %>
        </a>
      <% end %>
      <% if false %>
        <% if images[0] %>
          <%= render "image", i: images[0] %>
        <% end %>
        <% if images[1] %>
          <%= render "image", i: images[1] %>
        <% end %>
        <% if images[2] %>
          <%= render "image", i: images[2] %>
        <% end %>
        <div class="col-3">
          <% if @artwork.more_images_allowed? %>
            <h5 class="pink pb-2">Add up to 3 images or videos</h5>
            <%= render "images/form", artwork: @artwork, image: @artwork.images.new %>
          <% end %>
        </div>
      <% end %>
    </div>
  </section>
  <div class="row mt-2">
    <div class="col-4">
      <div><strong><%= @artwork.title %></strong> (<%= @artwork.year %>)<br>
        <%= @artwork.medium %>
      </div>
      <% if @artwork.edition.present? %>
        <div>
          ed: <%= @artwork.edition %>
        </div>
      <% end %>
      <%= render "dimensions" %>
      <div>
        Location: <%= @artwork.location %>
      </div>
      <div>
        Price: <%= @artwork.price.present? ? number_to_currency(@artwork.price, unit: "", precision: 0) : "none" %>
      </div>
      <div class="pink">
        <%= @artwork.visible ? "Not " : "" %> Visible to Curators
      </div>
      <% if @artwork.description.present? %>
        <div class="mt-2">
          <div class="fw-bold">Description</div>
          <%= @artwork.description %>
        </div>
      <% end%>
    </div>
    <div class="col-4 mt-2">
      <%= button_to "Edit this artwork", edit_artwork_path(@artwork), class: "btn btn-primary mb-4" %>
      <%= button_to "Delete this artwork", @artwork, method: :delete, class: "btn btn-danger", form: { data: { turbo_confirm: 'Are you sure?' } }, class: "btn btn-danger mt-4" %>
    </div>
  </div>
</div>

app/views/curator/artworks/_artwork.html.erb
<tr>
  <td><%= artwork.id %></td>
  <td><%= artwork.user.name %></td>
  <td><%= link_to artwork.title, curator_artwork_url(artwork) %></td>
  <td><%= artwork.medium %></td>
  <td width="300px"><%= artwork.description %></td>
  <td>
    <% artwork.images.each do |image| %>
      <%= image_tag thumbnail_url(image)  %>
    <% end %>
  </td>
</tr>

app/views/curator/artworks/index.html.erb
<h4>Artworks</h4>
<table class="table">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Artist</th>
      <th scope="col">Title</th>
      <th scope="col">Medium</th>
      <th scope="col">Description</th>
      <th scope="col">&nbsp;</th>
    </tr>
  </thead>
  <tbody id="artworks">
    <% @artworks.each do |artwork| %>
      <%= render artwork %>
    <% end %>
  </table>
</div>

app/views/curator/artworks/show.html.erb
<div class="container">
  <section class="image-grid">
    <div class="row gy-4">
      <% @artwork.images.each do |i| %>
        <div class="col-4">
          <%= image_tag large_url(i), alt: i.caption, class: "img-fluid" %>
          <i><%= i.caption %></i>
        </div>
      <% end %>
    </div>
  </section>
  <div class="row mt-4">
    <div class="col-6">
      <div><strong><%= @artwork.title %></strong> (<%= @artwork.year %>) by <%= @artwork.user.name %><br>
        <%= @artwork.medium %>
      </div>
      <% if @artwork.edition.present? %>
        <div>
          ed: <%= @artwork.edition %>
        </div>
      <% end %>
      <%= render "artworks/dimensions" %>
      <div>
        Location: <%= @artwork.location %>
      </div>
      <div>
        Price: <%= @artwork.price.present? ? @artwork.price : "none" %>
      </div>
      <% if @artwork.description.present? %>
        <div class="mt-2">
          <div class="fw-bold">Description</div>
          <%= @artwork.description %>
        </div>
      <% end%>
    </div>
  </div>
</div>

app/views/images/_form.html.erb
<%= bootstrap_form_with(model: [artwork, image]) do |f| %>
  <%= f.alert_message "Please fix the errors below." %>
  <%= f.text_field :caption, label: "Caption", class: "form-control-sm", help: "required" %>
  <%= f.file_field :file, class: "form-control-sm" %>
  <%= f.submit "Save" %>
<% end %>

app/views/images/_image.html.erb
<div id="<%= dom_id image %>">
  <div>
    <%= image_tag image.file.url(transformation: [{width: 300}]) %>
  </div>
  <p>
    <i><%= image.caption %></i>
  </p>
</div>

app/views/images/edit.html.erb
<div class="container col-md-5">
  <h4>Editing image for "<%= @artwork.title %>"</h4>
  <%= render "form", image: @image %>
  <br>
  <div>
    <%= link_to "Back to images", artwork_images_path(@artwork) %>
  </div>

app/views/images/index.html.erb
<h4>Images</h4>
<div id="images">
  <% @images.each do |image| %>
    <%= render image %>
  <% end %>
</div>
<%= link_to "New image", new_artwork_image_path %>

app/views/images/new.html.erb
<div class="container col-md-5">
  <h4>New image for "<%= @artwork.title %>"</h4>
  <%= render "form", artwork: @artwork, image: @image %>
  <br>
  <div>
    <%= link_to "Back to images", artwork_images_path(@artwork) %>
  </div>
</div>

app/views/images/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @image %>

<div>
  <%= link_to "Edit this image", edit_image_path(@image) %> |
  <%= link_to "Back to images", images_path %>

  <%= button_to "Destroy this image", @image, method: :delete %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">
      <img src="/logo.png" alt="Netvvrk Members Database" height="32" width="32">
      <span class="site-name">Netvvrk Members Database</span>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarToggler">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <% user = current_user %>
          <% if user.show_artworks? %>
            <li class="nav-item">
              <%= link_to "Artworks", artworks_url, class: "nav-link" %>
            </li>
          <% end %>
          <% if user.show_browse? %>
            <li class="nav-item">
              <%= link_to "Browse Artworks", curator_artworks_url, class: "nav-link" %>
            </li>
          <% end %>
          <% if user.show_users? %>
            <li class="nav-item">
              <%= link_to "Users", users_url, class: "nav-link" %>
            </li>
          <% end %>
        <% end %>
      </ul>
      <div class="d-flex" role="search">
        <% if user_signed_in? %>
          <span class="text-white"> <%#= current_user.email %></span>
          <%= button_to(
          "Log Out",
          logout_path,
          method: :delete,
          class: "btn btn-secondary"
        ) %>
        <% else %>
          <%= button_to(
          "Log In",
          login_path,
          method: :get,
          class: "btn btn-secondary"
        ) %>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Netvvrk Members Database</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true, type: "module" %>
  </head>
  <body>
    <%= render "layouts/navbar" %>
    <div class="container mx-2 my-4">
      <% flash.each do |_key, value| %>
        <div class="text-danger fw-bold my-2">
          <%= value %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :role, style: "display: block" %>
    <%= form.number_field :role %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <tr>
    <td><%= user.id %></td>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.role %></td>
    <td><%= user.active %></td>
    <td><%= user.last_sign_in_at&.to_date&.to_fs(:long) %></td>
  </tr>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<h4>Users</h4>
<table id="users" class="table">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Name</th>
      <th scope="col">E-mail</th>
      <th scope="col">Role</th>
      <th scope="col">Active</th>
      <th scope="col">Last Signed In</th>
      <th scope="col">&nbsp;</th>
    </tr>
  </thead>
  <tbody id="users">
    <% @users.each do |user| %>
      <%= render user %>
    <% end %>
  </table>
</div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>